// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1tiiqVW8Uwzf1C46w43xI7FV_zXp93Q8',
    appId: '1:354122565777:web:1bbed5c118aebfca475730',
    messagingSenderId: '354122565777',
    projectId: 'alcot-bf504',
    authDomain: 'alcot-bf504.firebaseapp.com',
    storageBucket: 'alcot-bf504.appspot.com',
    measurementId: 'G-T2JXVZKD92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrVgNgypOV5FSmeZII9wBRPJPZosoGp6g',
    appId: '1:354122565777:android:4317c18d1b04ec62475730',
    messagingSenderId: '354122565777',
    projectId: 'alcot-bf504',
    storageBucket: 'alcot-bf504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgplQFWmVDF_nK2mi_YeYs-9ZhM8PRvJI',
    appId: '1:354122565777:ios:2d65eab34fcacf05475730',
    messagingSenderId: '354122565777',
    projectId: 'alcot-bf504',
    storageBucket: 'alcot-bf504.appspot.com',
    iosBundleId: 'com.example.alcoTDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgplQFWmVDF_nK2mi_YeYs-9ZhM8PRvJI',
    appId: '1:354122565777:ios:2d65eab34fcacf05475730',
    messagingSenderId: '354122565777',
    projectId: 'alcot-bf504',
    storageBucket: 'alcot-bf504.appspot.com',
    iosBundleId: 'com.example.alcoTDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1tiiqVW8Uwzf1C46w43xI7FV_zXp93Q8',
    appId: '1:354122565777:web:36bde18f968b71f9475730',
    messagingSenderId: '354122565777',
    projectId: 'alcot-bf504',
    authDomain: 'alcot-bf504.firebaseapp.com',
    storageBucket: 'alcot-bf504.appspot.com',
    measurementId: 'G-7VM6JB8H8W',
  );
}
